### PR TITLE
fixed water graphics

### LINKED ISSUE #3: Water tile has no graphic

### PR DESCRIPTION
**Pull request by jamiahuswalton**
I added the "+" symbol for the water.

I change the water passable to true so we can all benefit to from the healing power 

This should resolve #3

### CODE REVIEW

File: Master-Game/World/WaterTile.cs [hunk 1]
```diff
@@ -9,10 +9,9 @@ namespace MasterGame.World
     class WaterTile : BaseTile
     {
         public WaterTile(int length, int width)
-            :base(TileType.Water, false, length, width, -10.0f)
+            :base(TileType.Water, true
```
Comment (havok13888) [inline Master-Game/World/WaterTile.cs]: keep them on the same line

File: Master-Game/Master-Game.csproj [hunk 2]
```diff
@@ -7,7 +7,8 @@
     <OutputType>Exe</OutputType>
     <RootNamespace>MasterGame</RootNamespace>
     <AssemblyName>Master-Game</AssemblyName>
-    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
+    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
```
Comment (havok13888) [inline Master-Game/Master-Game.csproj]: you need to update to 4.7
